import { Command, InvalidOptionArgumentError } from 'commander';
import { pathToFileURL } from 'node:url';

import { startDashboardServer } from './dashboard/server.js';

export { createUsageLoggerMiddleware } from './usage-logger.js';
export { startDashboardServer } from './dashboard/server.js';

if (isCliInvocation(import.meta.url)) {
  runCli().catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}

async function runCli(): Promise<void> {
  const program = new Command();

  program
    .name('llm-usage-ts')
    .description('Utilities for exploring and inspecting LLM usage logs');

  program
    .command('dashboard')
    .argument('<dbPath>', 'Path to the SQLite database generated by the usage middleware')
    .option('-p, --port <port>', 'Port to bind the dashboard server', '4545')
    .option('--host <host>', 'Host to bind the dashboard server', '127.0.0.1')
    .action(async (dbPath: string, options: { port?: string; host?: string }) => {
      const port = options.port ? Number.parseInt(options.port, 10) : 4545;
      if (!Number.isInteger(port) || port <= 0) {
        throw new InvalidOptionArgumentError('Port must be a positive integer.');
      }
      const host = options.host ?? '127.0.0.1';
      await startDashboardServer({ dbPath, port, host });
    });

  await program.parseAsync(process.argv);
}

function isCliInvocation(moduleUrl: string): boolean {
  const entryPoint = process.argv?.[1];
  if (!entryPoint) return false;
  try {
    return pathToFileURL(entryPoint).href === moduleUrl;
  } catch {
    return false;
  }
}
